# Generated by Django 3.1.7 on 2021-05-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_group_payments', '0002_auto_20210527_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffworkerpayment',
            name='pay_date',
        ),
    ]
