# Generated by Django 3.1.7 on 2021-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffaddress',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
