# Generated by Django 3.1.7 on 2021-05-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdeliver',
            name='removed_date',
        ),
        migrations.RemoveField(
            model_name='staffmanager',
            name='removed_date',
        ),
        migrations.RemoveField(
            model_name='staffseller',
            name='removed_date',
        ),
        migrations.RemoveField(
            model_name='staffworker',
            name='removed_date',
        ),
    ]
